host: "localhost"
port: 3306
db: "smartcraft"
user: ""
password: ""
column: ""
stats:
  - monsters
  - money
  - airdrop
text:
  monsters: "Убийство монстров"
  money: "Деньги"
  airdrop: "Аирдропы"
places: